internal/telemetry/meter/meter.go

Uniswap
- https://uniswap.org/
- https://uniswap.org/developers
- Ethereum
- Polygon
- Optimistic
- Arbitrum
- UniversalRouter https://etherscan.io/address/0xef1c6e67703c7bd7107eed8303fbe6ec2554bf6b
- NonfungiblePositionManage https://etherscan.io/address/0xC36442b4a4522E871399CD717aBDD847Ab11FE88
- Uni https://etherscan.io/address/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984
- https://etherscan.io/tx/0xbd134c2b8b9136208df346927569933521e854a23c771b2dd1746e7b19f10d97
- https://etherscan.io/tx/0xf82bd3d38b4c17821ed0c6d895a1a3951fec3b7f74c7089239e4e55c27f24238

feat(meter): add `/healthcheck` path for internal meter http server

---

README.md

docs: remove deploy status badges

---

schema/filter/tag_type.go

fix: missing type string

---

schema/filter/ethereum_chain_string.go
schema/filter/network.go

missing comments after ethereum chain id generation

fix: missing comments after ethereum chain id generation

---

schema/filter/network.go

fix: missing Avalanche network

---

cmd/main.go
config/config.go
config/config_test.go
go.mod
internal/engine/source/ethereum/option.go

fix(parameter): add more test and fix command line parameter

---

deploy/config.development.yaml
internal/engine/worker/contract/iqwiki/worker.go
provider/ethereum/contract/matters/contract.go

fix(iqwiki): ignore iqwiki graphql err

---

README.md

chore: rename SN to Node

---

cmd/main.go
go.sum
internal/node/broadcaster/handler.go
internal/node/broadcaster/server.go

feat: add broadcaster node info api

---

deploy/config.development.yaml
go.mod
go.sum
internal/engine/worker/contract/opensea/worker.go

handle non-standard token as unknown feed
Resolve #137 temporarily

fix: handle non-standard token as unknown feed

---

internal/engine/source/ethereum/source.go

fantom and arbitrum get block receipts issue

fix: fantom and arbitrum get block receipts issue

---

.github/workflows/docker-build.yaml
Dockerfile

add default config file in dockerfile and support more system arch

chore: add default config file in dockerfile and support multi platform

---

.github/workflows/docker-build.yaml
Dockerfile

chore(docker): update multi-arch build image

---

.github/workflows/docker-build.yaml

ci: fix docker images

---

Dockerfile
cmd/main.go
config/config_test.go
deploy/config.yaml
internal/node/broadcaster/handler.go

chore: rename config file

---

.github/workflows/docker-build.yaml

build: multi arch optimization

---

.github/workflows/docker-build.yaml

ci: merge image digest

---

go.mod
go.sum

update protocol-go to v0.2.0 and release node v0.2.0

chore: update protocol-go to v0.2.0

---

internal/node/indexer/server.go

add latest block/height in opentelemetry metrics
Resolve #151

feat: add latest block/height in opentelemetry metrics

---

provider/farcaster/client_test.go

remove farcaster test due to unstable public url

fix(farcaster): remove farcaster test due to unstable public url

---

internal/engine/worker/contract/aave/worker.go

aave panic due to nil transaction to

fix: aave panic due to nil transaction to

---

internal/engine/worker/contract/aave/worker.go
internal/engine/worker/contract/highlight/worker.go
internal/engine/worker/contract/lido/worker.go
internal/engine/worker/contract/looksrare/worker.go
internal/engine/worker/contract/matters/worker.go
internal/engine/worker/contract/opensea/worker.go

ignore anonymous logs in transform logic

fix: ignore anonymous logs in transform logic

---

internal/engine/worker/contract/iqwiki/worker.go
internal/engine/worker/contract/iqwiki/worker_test.go
internal/engine/worker/factory.go
provider/ipfs/client_http_test.go

use vault rpc value in iqwiki worker

fix: use vault rpc value in iqwiki worker

---

internal/node/hub/rss/data.go

fix: modify rsshub ums query param

---

go.mod
go.sum
internal/engine/worker/fallback/ethereum/worker_test.go
provider/ethereum/contract/multicall3/contract.go
provider/ethereum/endpoint/endpoint.go
provider/ethereum/token/client.go
provider/ethereum/token/client_test.go

change rss3 network name to vsl

feat: change rss3 network name to vsl

---

go.mod
go.sum
internal/engine/source/ethereum/source.go

fix: bsc and linea network

---

internal/engine/worker/contract/matters/worker_test.go
provider/ethereum/etherface/client.go

change etherface endpoint to self-hosted service

feat: change etherface endpoint to self-hosted service

---

go.mod
go.sum
internal/engine/worker/factory.go

fix: add vsl factory

---

internal/node/indexer/server.go

perf(worker): increase task channel to 200

---

internal/engine/source/arweave/option.go
internal/engine/source/ethereum/option.go

add source option thread rpc json tag

fix: add source option thread rpc json tag

---

internal/database/dialer/cockroachdb/client.go
internal/node/indexer/server.go

fix: add db retry logic

---

internal/node/indexer/server.go

chore(indexer): remove transactions for database feeds and checkpoints

---

internal/database/dialer/cockroachdb/client.go

chore(database): set the param `SkipDefaultTransaction` of gorm true

---

internal/database/dialer/cockroachdb/client.go

fix: add more db retry match logic

---

internal/database/dialer/cockroachdb/client_partitioned.go

chore(database): delete indexes in batches

---

go.mod
go.sum
provider/ethereum/token/client.go

feat: move get token uri call to parseTokenmetadata logic

feat: move get token uri call to parseTokenmetadata logic

---

internal/database/dialer/cockroachdb/client_partitioned.go

Related https://github.com/RSS3-Network/Node/issues/202

perf(database): increase concurrency to write indexes

---

cmd/main.go

fix: flush the logs before the process exits

---

provider/ethereum/client.go

fix(provider/ethereum): batch request results may contain null values

---

common/sync/quickgroup.go
common/sync/quickgroup_test.go

https://github.com/RSS3-Network/Node/actions/runs/8783817867/job/24100765457#step:6:725

fix(common/sync): quickgroup has a data race issue

---

internal/engine/source/arweave/source.go

```plaintext
Container is waiting because of CrashLoopBackOff. It is not started and not ready.
The container last terminated with exit code 137 because of OOMKilled.
```
https://flamegraph.com/share/0fe2fdbf-0229-11ef-8204-e6b38c1ccd74

fix(source/arweave): unfiltered arweave batch transactions

---

schema/worker/worker.go
schema/worker/worker_string.go

worker name change: `oneinch` -> `1inch`

fix: 1inch worker name

---

deploy/config.yaml
schema/worker/worker.go
schema/worker/worker_string.go

fix uniswap worker name and change order

fix: uniswap worker name and change order

---

config/config_test.go
schema/worker/worker.go
schema/worker/worker_string.go

change worker enum type to Int

fix: change worker enum type to Int

---

internal/engine/source/ethereum/source.go

```json
{"level":"fatal","ts":1714469197.733994,"caller":"cmd/main.go:227","msg":"execute command","error":"an error occurred in the source: get logs by filter: end (19767223) < begin (19767224)","stacktrace":"main.main\n\t/root/node/cmd/main.go:227\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}
```
```json
{"level":"fatal","ts":1714469404.297533,"caller":"cmd/main.go:227","msg":"execute command","error":"an error occurred in the source: get logs by filter: begin block 44849254 is greater than end block 44849253","stacktrace":"main.main\n\t/root/node/cmd/main.go:227\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}
```

fix(source/ethereum): incorrectly calculated filter block ranges

---

internal/engine/source/arweave/source.go
internal/engine/source/ethereum/source.go
internal/engine/source/farcaster/source.go
internal/node/indexer/server.go

Because worker exit will cause additional losses, retry logic needs to be added.

feat: add retry logic in indexers and sources

---

internal/engine/worker/contract/momoka/worker_test.go

test: image url in momoka test

---

internal/engine/source/ethereum/task.go
provider/ethereum/type.go

feat(source/ethereum): support eip-2718 transaction for arbitrum

---

cmd/main.go
config/config.go
config/flag/config.go
deploy/config.yaml
internal/node/indexer/server.go
internal/node/monitor/monitor.go
internal/node/monitor/monitor_mock.go
internal/node/monitor/monitor_test.go
internal/node/node.go

Resolved #262.
```diff
+   - id: ethereum.core
-   - network: ethereum
network: ethereum
worker: core
endpoint: ethereum
parameters:
block_number_start:
```
```
rss3-node --indexer.network=ethereum --indexer.worker=core --indexer.parameters={}
```
```
rss3-node --worker.id=ethereum.core
```

feat: support for customized worker

---

deploy/config.yaml

chore(config): update the example of endpoints

---

deploy/config.yaml
internal/node/component/decentralized/handler_workers.go
internal/node/component/decentralized/handler_workers_test.go
internal/node/indexer/server.go
internal/node/monitor/monitor.go
internal/node/monitor/monitor_mock.go
internal/node/monitor/monitor_test.go
schema/worker/status.go
schema/worker/status_string.go

1. remove disabled status
2. move ready checking logic to monitor module
3. modify status checking logics in monitor module
4. add worker aggregate logic in component module

feat(module/monitor): adjust monitor and add worker aggregate logic in component

---

internal/engine/source/arweave/source.go

fix(source): fix the logic of matching bundlr nodes

---

internal/engine/worker/contract/curve/worker.go
provider/ethereum/contract/curve/contract.go

fix: curve matching logic

---

internal/engine/source/arweave/source.go

fix(source/arweave): filter bundle transactions in batchPullData

---

internal/engine/worker/contract/stargate/worker.go
internal/engine/worker/contract/stargate/worker_test.go
provider/ethereum/contract/layerzero/contract.go
provider/ethereum/contract/stargate/contract.go

fix: stargate source filter logic

fix: stargate source filter logic

---

internal/engine/source/arweave/source.go

fix(source/arweave): used invalid owner when filtering data

---

internal/node/component/network/relation.go

fix: set config worker id as required

fix: set config worker id as required

---

deploy/config.yaml
internal/node/indexer/server.go
internal/node/monitor/client.go
internal/node/monitor/monitor.go
internal/node/monitor/monitor_mock.go
internal/node/monitor/monitor_test.go
internal/node/monitor/server.go

1. move unknown -> indexing status to monitor module
2. add workers with target param extra logic

fix(module/monitor): handling unknown status and add extra logic for workers with target param

---

internal/engine/source/arweave/source.go

https://viewblock.io/arweave/block/1187748
https://viewblock.io/arweave/tx/4mdtwXkR3V9qzA2haO0TG2mgl2bhanROywKPVu6QkCQ
https://viewblock.io/arweave/tx/fnsyKm1hw4xSFqXkmJ4HzPrK8wZnlpEJjGcDDn3iXvI
```bash
$ sha1sum 4mdtwXkR3V9qzA2haO0TG2mgl2bhanROywKPVu6QkCQ fnsyKm1hw4xSFqXkmJ4HzPrK8wZnlpEJjGcDDn3iXvI
225c6bcb20b39b1557c80fa88ff3960dcc901031  4mdtwXkR3V9qzA2haO0TG2mgl2bhanROywKPVu6QkCQ
225c6bcb20b39b1557c80fa88ff3960dcc901031  fnsyKm1hw4xSFqXkmJ4HzPrK8wZnlpEJjGcDDn3iXvI
```

fix(source/arweave): bundlr has duplicate bundle transactions

---

internal/node/component/network/config.go
internal/node/component/network/handler_network.go
internal/node/component/network/handler_network_test.go
internal/node/component/network/resource.go

add resource calculation in network config api

feat: add resource calculation in network config api

---

internal/engine/worker/contract/momoka/worker.go
internal/engine/worker/contract/paragraph/worker.go
provider/arweave/client.go

feat(arweave): adjust the retry strategy of arweave gateways

---

config/config.go
go.mod
provider/arweave/gateway.go

add more default arweave gateways and set endpoint config not required

chore: add more default arweave gateways

---

Makefile
config/parameter/network.go
internal/node/component/network/component.go
internal/node/component/network/config.go
internal/node/component/network/handler_network.go
internal/node/component/network/handler_network_test.go
internal/node/component/network/resource.go

feat: add get endpoint config api

---

internal/node/broadcaster/broadcaster.go

chore(broadcaster): display more accurate error information

---

internal/node/broadcaster/server.go

remove http server in braodcaster

fix(module/broadcaster): remove http server in braodcaster

---

.github/workflows/build-readme.yaml
README.md
build_readme.py

add auto-generate network worker table script and ci
Should resolve #282

ci(README.md): add auto-generate network worker table script and ci

---

.github/workflows/build-readme.yaml

use pull-requests to update network and worker table
- will run everyday
- can be triggered manually
- will close old pr automatically
- [] Tests for the changes have been added (for bug fixes / features);

fix: use pull-requests to update network and worker table

---

.github/dependabot.yml
.github/workflows/build-readme.yaml

change dependabot trigger branch to develop

chore: enable dependabot

---

.github/dependabot.yml

ci: add more dependabot items

---

internal/database/dialer/cockroachdb/client_partitioned.go

fix(database): resolve blocking caused by empty value

---

internal/engine/source/arweave/source.go
provider/arweave/client.go

chore(source): update the number of arweave concurrencies

---

internal/node/component/network/config.go

fix(networks): rename endpoint type

---

internal/engine/source/arweave/option.go
internal/engine/source/arweave/source.go
provider/arweave/client.go
provider/arweave/gateway.go

chore(source): optimize the logic of arweave pulling data

---

config/parameter/network.go
internal/engine/source/arweave/option.go
internal/engine/source/arweave/source.go

fix(source/arweave): incorrect block range calculation

---

internal/engine/source/arweave/option.go
internal/engine/source/ethereum/option.go

fix(indexer): resolve empty option

---

internal/database/model/activity.go
internal/node/component/decentralized/handler_activity.go
schema/worker/platform.go

fix(hub): resolve platform parameter parsing

---

internal/node/component/network/config.go

Set the default parameter value for the worker configuration to null

chore: set default param value for worker config to null

---

internal/node/component/network/config.go

Revert "chore: set default param value for worker config to null"

---

docs/openapi.go
docs/openapi.json

feat(docs): write the generated enum to the openapi file

---

docs/openapi.go

chore(docs): ignore errors in writing files

---

internal/node/component/info/handler_worker.go
internal/node/component/info/handler_workers_test.go
internal/node/monitor/monitor.go
internal/node/monitor/monitor_mock.go
internal/node/monitor/monitor_test.go
provider/ethereum/token/client.go
provider/farcaster/client_test.go

add worker progress in workers_status api
should Resolve #354

feat: add worker progress in workers_status api

---

internal/node/component/component.go
internal/node/component/decentralized/component.go
internal/node/component/decentralized/handler_activity.go
internal/node/component/info/component.go
internal/node/component/info/handler_network.go
internal/node/component/info/handler_node.go
internal/node/component/info/handler_worker.go
internal/node/component/rss/component.go
internal/node/component/rss/handler.go

add core module api tracer
should resolve #358

feat(module/core): add core module api tracer

---

internal/node/component/decentralized/component.go
internal/node/component/decentralized/handler_activity.go

add `/decentralized/accounts` api to get multiple accounts' activities in a single request.
should resolve #401

feat(core): add batch query accounts activities api

---

docs/openapi.json
internal/database/dialer/cockroachdb/client_partitioned.go
internal/node/component/decentralized/component.go
internal/node/component/decentralized/handler_activity.go
internal/node/component/decentralized/handler_network_activity.go
internal/node/component/decentralized/handler_platform_activity.go

feat(component): add network and platform api for decentralized

---

docs/openapi.json

chore(docs): remove dsl tag for openapi

---

.github/dependabot.yml
go.mod
go.sum

degrade protocol-go dep version

chore: degrade protocol-go dep version

---

cmd/main.go
internal/node/component/info/handler_activity.go
internal/node/component/info/handler_worker.go
internal/node/monitor/server.go

Related Issue: https://github.com/RSS3-Network/Node/issues/258

feat: reduce dependencies for rss nodes

---

go.mod
go.sum
internal/engine/source/ethereum/data_source.go
internal/node/component/decentralized/data.go

update samber/lo dep
`samber/lo` has breaking change in `lo.Last`, causing #423 failed.

chore: update samber/lo dep

---

config/config.go
config/config_test.go
deploy/config.example.yaml
deploy/example/config.min.yaml

feat: add normal type for node

---

config/config.go
config/config_test.go

remove keys iter and add env override test

fix(config): remove keys iter

---

Dockerfile
deploy/sample/config.sample.yaml

feat: add sample config file as default config

---

docs/openapi.json
internal/node/component/info/handler_node.go

1. change worker coverage from rate to worker list
2. fix gi reward data

fix: change worker coverage type and reward logic

---

config/parameter/data.go

change store data range to 4 months

chore(config): change store data range to 4 months

---

config/config.go
config/config_test.go
deploy/config.example.yaml
deploy/sample/config.sample.yaml
internal/node/component/info/handler_node.go
internal/node/component/info/handler_worker.go
internal/node/component/rss/component.go
internal/node/monitor/client.go
internal/node/monitor/monitor.go
internal/node/monitor/monitor_mock.go
internal/node/monitor/monitor_test.go
internal/node/monitor/server.go
internal/node/node.go

1. updated RSS component configuration to reflect single worker setup
2. modify the heartbeat interface of rsshub
affected interfaces are:
/workers_status

feat: rss config

---

.github/workflows/docker-build.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml

ci: add prod branch for release

---

internal/engine/worker/decentralized/core/ethereum/worker.go
provider/ethereum/contract/vsl/abi/L2StandardBridge.abi
provider/ethereum/contract/vsl/contract_l2_standard_bridge.go

fix vsl bridge filterer init logic

fix: vsl bridge filterer init logic

---

internal/engine/worker/decentralized/contract/vsl/worker.go
internal/engine/worker/decentralized/contract/vsl/worker_test.go
internal/engine/worker/decentralized/core/ethereum/worker.go
internal/engine/worker/decentralized/core/ethereum/worker_test.go
internal/engine/worker/decentralized/factory.go
internal/node/component/info/network_config.go
schema/worker/decentralized/platform.go
schema/worker/decentralized/worker.go
schema/worker/decentralized/worker_string.go

1. remove platform in vsl core worker
2. bring back ethereum vsl worker
3. adjust worker configs

feat: bring back vsl worker

---

config/config_test.go
internal/engine/worker/decentralized/contract/rss3/worker.go
internal/node/component/info/handler_worker.go
provider/ipfs/gateway.go
schema/worker/decentralized/worker.go

add tags in different core workers

fix(core): add tags in core workers_status

---

internal/database/dialer/cockroachdb/client_partitioned.go

feat(database): remove the specified index

---

internal/engine/source/ethereum/data_source.go

xlayer source get receipts issue

fix: xlayer source get receipts issue

---

.devcontainer/docker-compose.yaml
deploy/config.example.yaml
deploy/example/config.min.yaml
deploy/example/docker-compose.example.yaml
deploy/sample/config.sample.yaml

1. fix postgres docker image tag and docker compose config
2. adjust example/sample config

fix(config): postgres docker compose and config

---

config/config.go
config/config_test.go
deploy/config.example.yaml
deploy/example/config.min.yaml
deploy/sample/config.sample.yaml
internal/node/broadcaster/broadcaster.go

chore(config): remove node type field

---

config/config.go

fix: add rss config check

---

docs/openapi.json

add endpoint_config openapi doc

docs: add endpoint_config openapi doc

---

internal/node/broadcaster/broadcaster.go

chore(broadcaster): add default type for node register

---

docs/openapi.json
internal/node/component/info/component.go
internal/node/component/info/handler_asset.go
internal/node/component/info/handler_worker.go

1. remove `/workers_info` api
2. move `/workers_info` logic to `/assets` and add network info
3. update openapi
Will reflect GI and Explorer logic

feat(core): add `/assets` api

---

deploy/min/config.min.yaml

add missing fields in min config

fix: add missing fields in min config

---

internal/node/component/info/handler_network.go
internal/node/component/info/network_config.go

remove mastodon network and add xlayer worker

feat(core): remove mastodon network and add x-layer core worker in config

---

deploy/min/docker-compose.min.yaml

chore: use node prod tag v1.0.0

---

internal/node/component/info/handler_asset.go
schema/worker/decentralized/worker.go

chore: change some network and worker icon to mono/alt

chore(core): change some network and worker icon to mono/alt

---

.github/workflows/docker-build.yaml

add condition in merge and push ci

ci: add condition in merge and push ci

---

internal/engine/worker/decentralized/contract/aave/worker.go

`Transform` has a log loop, but `handle...` functions ran it again, which pass all test cases but is not correct.

fix(worker/aave): unexpected double loop

---

tool/testcase/main.go
tool/testcase/template/ethereum.tmpl

also generate network in testcase according to rpc request.

fix: add network in ethereum testcase template

---

internal/node/component/info/network_config.go

fix: add missing 1inch config

---

.github/workflows/docker-build.yaml

chore: use google artifact registry

---

.github/workflows/docker-build.yaml

ci: add worker-dev branch trigger

---

cmd/main.go

chore: return error when parsing network parameters failed

---

.pre-commit-config.yaml

add gitleaks to pre-commit hooks

chore: add gitleaks to pre-commit hooks

---

internal/node/monitor/server.go

init near source network client in monitor

fix(monitor): init near source network client in monitor

---

internal/node/broadcaster/broadcaster.go

add semantic version in node registration
should resolve #550

feat: add semantic version in node registration

---

deploy/config.example.yaml
docs/openapi.json
internal/node/component/info/handler_network.go
internal/node/component/info/network_config.go

1. add federated example config file
2. change rss config to object
3. add default network endpoint url

feat: change rss to object and add default network endpoint url

---

docs/openapi.json
internal/node/component/info/handler_network_test.go
internal/node/component/info/network_config.go
internal/node/component/info/network_resource.go

add title and key in config detail

feat: add title and key in config detail

---

internal/node/component/info/handler_network.go

reorder the worker configs
- core worker first
- others in alphabetical order

chore: reorder the worker configs

---

internal/node/component/info/handler_network.go
internal/node/component/info/network_config.go

change mastodon endpoint type to string

fix: change mastodon endpoint type to string

---

docs/openapi.json
internal/node/component/info/handler_network.go

add default worker endpoint value

fix: add default worker endpoint value

---

docs/openapi.json
internal/engine/worker/decentralized/contract/arbitrum/worker.go
internal/engine/worker/decentralized/contract/base/worker.go
internal/engine/worker/decentralized/contract/linea/worker.go
internal/engine/worker/decentralized/contract/optimism/worker.go
internal/node/component/info/network_config.go

feat: bridging workers configs

---

provider/ethereum/contract/vsl/contract.go

Should be merged later (before release)

chore: update network params contract address

---

deploy/config.example.yaml
deploy/min/config.min.yaml

chore(config): update mastodon worker name

---

deploy/config.example.yaml

chore: update redis config desc

---

go.mod
go.sum
internal/engine/worker/decentralized/contract/nouns/worker.go
internal/engine/worker/decentralized/contract/nouns/worker_test.go

fix: add nouns proposal options

---

internal/node/component/info/network_config.go

chore: update network configs

---

go.mod
go.sum
internal/engine/worker/decentralized/contract/nouns/worker.go
internal/engine/worker/decentralized/contract/nouns/worker_test.go
internal/node/component/info/network_config.go

fix(worker/nouns): add nouns proposal options

---

internal/node/component/info/handler_node.go

chore(component): add more logs for info

---

.gitignore
cmd/main.go
config/config.go
docs/openapi.json
internal/node/component/info/handler_node.go
internal/node/component/info/handler_worker.go
internal/node/component/rss/component.go
internal/node/component/rss/handler.go

fix: `/info` api when no decentralized workers

---

cmd/main.go

record first start time in core module

fix: record first start time in core module

---

deploy/config.example.yaml
deploy/default/config.default.yaml
deploy/min/config.min.yaml

fix: update rsshub default config

---

go.mod
go.sum

upgrade protocol-go to v0.5.14

chore: upgrade protocol-go to v0.5.14

---

internal/node/component/decentralized/handler_activity.go

fix(component): fix forced convert account encoding format

---

internal/database/dialer/postgres/client_partitioned.go

fix(monitor): avoid dirty data in indexes table

---

internal/node/component/info/handler_node.go

Use `_` to separate network and worker

feat: add network in worker coverage info

---

internal/node/indexer/server.go

Filter out activities with non-existent actions

fix: filter out activities with non-existent actions

---

internal/database/client.go
internal/database/dialer/postgres/client.go
internal/database/dialer/postgres/client_partitioned.go
internal/database/dialer/postgres/client_test.go
internal/database/dialer/postgres/table/activity.go
internal/node/indexer/server.go

Avoid the fallback core worker from overwriting valid activities

fix(database): resolve data write conflicts

---

internal/database/dialer/postgres/client_partitioned.go

resolve https://github.com/RSS3-Network/Node/issues/646

fix: add double quotes to the table name

---

config/config.go
config/config_test.go
deploy/config.example.yaml
deploy/default/config.default.yaml
deploy/min/config.min.yaml
internal/database/dialer/dialer.go
internal/database/dialer/postgres/client_test.go
internal/engine/worker/decentralized/contract/ens/worker_test.go
internal/engine/worker/decentralized/contract/mirror/worker_test.go
internal/engine/worker/federated/core/mastodon/worker_test.go
internal/stream/provider/provider.go
provider/redis/client.go

feat: remove redundant configs

---

docs/openapi.json
internal/node/component/info/handler_node.go

Add supported & unsupported lists of different type of workers so operators can better know how can they earn more rewards.
Resolve #633

feat: enrich worker coverage response

---

internal/node/monitor/monitor.go

fix: add federated worker index count

---

internal/node/indexer/server.go

fix(monitor): resolve the empty monitor client

---

internal/node/component/ai/handler.go

fix(handler): improve query parsing in agentdata path handling

---

internal/node/component/ai/handler.go

fix(handler): improve query handling in agentdata path processing

---

deploy/default/config.default.yaml

chore: remove decentralized

---

internal/node/monitor/monitor_mock.go

remove redundant words in comment

chore: remove redundant words in comment
