RSS3-Network/Node

- .github/workflows/docker-build.yaml
- Dockerfile
docker build would be triggered by 
- branch develop
- tags
- pull_request
but `github.ref == 'refs/heads/develop'` only works with branch develop, tags will be skip, set `github.event_name != 'pull_request'` to cover tags event
> chore: fix docker push

- deploy/config.yaml
- internal/engine/source/farcaster/option.go
- internal/engine/source/farcaster/source.go
- provider/farcaster/client.go
If the Farcaster URL requires an API key, you should include the api_key in the config parameters.
> fix: upgrade farcaster url

- internal/engine/source/ethereum/source.go
get receipts by block number not support
> fix(source/savm): get receipts by block number not support

- internal/database/dialer/cockroachdb/client.go
add encountered recently written committed value tx catch logic
> fix: add encountered recently written committed value tx catch logic

- go.mod
- go.sum
- internal/engine/source/ethereum/option.go
- internal/engine/source/ethereum/source.go
- provider/ethereum/client.go
The concurrency of HTTP requests has been reduced now. If a chain does not support the `eth_getBlockReceipts` method, there are **200** transactions for each of the **8** blocks. The source needs to send **1608** `8 (eth_getBlockByNumber) + 8 * 200 (eth_getTransactionReceipts)` HTTP requests. Now with the default parameters, it only needs **9** `1 (batch size of 8 for eth_getBlockByNumber) + 8 (batch size of 200 for eth_getTransactionReceipts)` HTTP requests.
The Binance Smart Chain also supports the `eth_getBlockReceipts` method, so it was removed from the list.
> perf(source/ethereum): support batch request for ethereum

- internal/engine/source/ethereum/source.go
Related to #202. In the previous implementation,  if we set the block batch size and number of block threads parameters of the Ethereum source to 8, and each block contained 200 transactions, there would be a total of 12,800 ( 8 * 8 * 200) transactions. In this case, the `buildTasks` function will repeatedly allocate a slice of length 200 a total of 12,800 times. This can cause significant memory allocation overhead.
- Before https://flamegraph.com/share/1755d160-fe03-11ee-8204-e6b38c1ccd74
- After https://flamegraph.com/share/0aba2f8c-fe03-11ee-a542-36adf59c1176
> perf(source/ethereum): avoid allocating too many duplicate large slice

- deploy/config.yaml
- internal/node/hub/rss/data.go
- internal/node/hub/rss/option.go
According to RSSHub doc: https://docs.rsshub.app/deploy/config#access-control-configurations
We will only allow users set access key in rss worker. And the node service will access the RSSHub instance only by code to avoid key leaking.
The code is generated using md5 `md5('/qdaily/column/59' + 'ILoveRSSHub')`
> fix: rsshub auth logic

- internal/engine/source/ethereum/task.go
Related #241. Incorrect use of Optimism's `l1Fee` field in Arbitrum.
> fix(source/ethereum): remove invalid transaction fee field for arbitrum

- deploy/config.example.yaml
- internal/engine/worker/contract/matters/worker.go
- internal/engine/worker/contract/matters/worker_test.go
- internal/node/component/network/relation.go
- tool/testcase/template/ethereum.tmpl
matters was on polygon network before block [53561096](https://polygonscan.com/block/53561096), the last tx is: [0x5edebbdae7b5c79a69aacf7873796bb1ec664db8](https://polygonscan.com/address/0x5edebbdae7b5c79a69aacf7873796bb1ec664db8)
now it's on Optimisim blockchain, the contract was deployed on block [117058632](https://optimistic.etherscan.io/block/117058632), the deployment tx is [0xfc7a79202bcb1b3060e3f4b409505009b9539e0e561d4bdb19743d1757b9efdb](https://optimistic.etherscan.io/tx/0xfc7a79202bcb1b3060e3f4b409505009b9539e0e561d4bdb19743d1757b9efdb)
this pr changes the network of matters worker, update test cases.
> fix: change matters network from polygon to optimism

- deploy/config.example.yaml
add global arweave endpoint in example config
> fix: add global arweave endpoint

- provider/ethereum/client.go
- provider/ethereum/client_test.go
Fixed the bug where the client was unable to distinguish if the result was nil or non-nil, causing the source to panic when it was nil.
> fix(provider/ethereum): invalid rpc result type for client

- config/parameter/network.go
We use network tolerance to monitor worker status. A threshold of 100 blocks is too strict for the Arbitrum and Crossbell blockchains, causing frequent changes from `ready` to `indexing` status.
> chore: adjust arbitrum and crossbell network tolerance

- config/config.go
- config/config_test.go
- deploy/config.example.yaml
- deploy/example/config.min.yaml
- internal/engine/worker/contract/curve/worker_test.go
- internal/engine/worker/core/ethereum/worker_test.go
- internal/node/monitor/monitor_test.go
- provider/redis/client.go
use string type in redis config instead of array
will affect our prod deployment @incubator4
> feat: use redis endpoint string instead of array

- Makefile
Add new make commands in the Makefile to simplify running the worker, core, monitor, and broadcaster services locally. This includes adding comments and notes for each command to provide clear instructions for developers.
> chore(makefile): add `make` commands for various Node services

- internal/node/component/decentralized/handler_activity.go
use hexToAddress to convert batch account query owners
> fix: use hexToAddress to convert batch account query owners

- docs/openapi.json
- internal/node/component/info/component.go
- internal/node/component/info/handler_node.go
bring node operator api back and add info route
> chore: bring node operator api back and add info route

- docs/openapi.json
- internal/node/component/info/handler_worker.go
- internal/node/monitor/monitor.go
- internal/node/monitor/monitor_mock.go
- internal/node/monitor/monitor_test.go
- internal/node/monitor/server.go
Add the `index_count` field to `/workers_status` without modifying existing fields. This change will not affect GI-related APIs. @brucexc
> feat: add index count in workers_status api

- config/config.go
- config/config_test.go
- docs/openapi.json
- internal/node/broadcaster/broadcaster.go
- internal/node/component/decentralized/component.go
- internal/node/component/middleware/auth.go
- internal/node/component/rss/component.go
- internal/node/node.go
It adds bearer token authentication for the `/decentralized` and `/rss` APIs.
should resolve #345 
**IMPORTANT**
Implementation requires addressing issue https://github.com/RSS3-Network/Node-Automated-Deployer/issues/22. @STRRL 
Before moving to production, GI must update the node API invocation logic to include authentication. @brucexc
> feat: add bearer token auth for /decentralized and /rss routers

- internal/engine/source/farcaster/data_source.go
- internal/engine/source/farcaster/option.go
- provider/farcaster/client.go
- provider/farcaster/client_test.go
To add a start timestamp to Farcaster and only retrieve data after the start timestamp.
`Start timestamp is in seconds`
related to https://github.com/RSS3-Network/Node/issues/485
> feat: add start timestamp to farcaster

- internal/node/component/info/handler_node.go
return 0x address when evm address is not set when query `/` api.
> fix(core): return 0x address when evm address is not set

- .github/workflows/release.yaml
use `changelogithub` to automatically release when creating a new tag.
> ci: add auto release with changelog ci

- internal/database/dialer/postgres/client_partitioned.go
- internal/node/monitor/cronjob.go
- internal/node/monitor/server.go
> feat(monitor): automatically release cronjob lock when program exits

- deploy/min/config.min.yaml
- deploy/min/docker-compose.min.yaml
Add mastodon worker template to YAML files for automatic deployment
> feat(deploy): add mastodon worker template for deployment

- docs/openapi.json
- go.mod
- go.sum
- internal/node/component/info/component.go
- internal/node/component/info/handler_network.go
add `networks/config` api that returns all config details so the explorer don't need to invoke multiple apis
**BE CAREFUL**
- will affect GI APIs @brucexc 
- will affect Explorer @songkeys 
- will affect build-readme github actions @pseudoyu
> feat: add `networks/config` api that returns all config details

- internal/node/component/info/handler_network.go
- internal/node/component/info/network_config.go
add mastodon related config details
> feat: add mastodon related config details

- internal/node/component/info/handler_network.go
remove rsshub endpoint default value
> chore: remove rsshub endpoint default value

- internal/database/dialer/postgres/table/activity.go
The index field is always 0 in the activity query results.
> fix: missing index in activity

- docs/openapi.json
- internal/node/component/info/component.go
- internal/node/component/info/handler_node.go
Add `/operators` route group.
May I only keep `/operators` route and GI will invoke different routes based on Node version or I just includes two versions? @brucexc 
And openapi docs is blocked by #599 @incubator4
> feat: use both `/` and `/operators` routes

- cmd/main.go
- config/config.go
- internal/node/component/info/component.go
- internal/node/component/info/handler_node.go
- internal/node/component/info/handler_worker.go
- internal/node/indexer/server.go
- internal/node/monitor/client.go
- internal/node/monitor/monitor.go
- internal/node/monitor/monitor_mock.go
- internal/node/monitor/monitor_test.go
- internal/node/monitor/server.go
fix `/workers_status` api fetchWorker logics
> fix: `/workers_status` api fetchWorker logics

- internal/node/monitor/server.go
remove rsshub config check logic from monitor
> fix: monitor rsshub check logic

- internal/engine/worker/decentralized/core/ethereum/worker.go
https://polygonscan.com/tx/0xda7953e0b756ddff528c1b9b74d0dff9f51298a6d8bdab8d592b76e9693d6a15#eventlog
In the transfer event log as shown in the link, a panic is triggered when the value is 0.
> fix: transfer value is zero

- internal/engine/worker/decentralized/contract/uniswap/worker.go
- internal/engine/worker/decentralized/contract/uniswap/worker_test.go
- provider/ethereum/contract/uniswap/contract.go
https://github.com/Uniswap/universal-router/blob/main/deploy-addresses/mainnet.json
> feat: add uniswap universal router in ethereum

- internal/engine/worker/rss/factory.go
> chore: remove redundant Func

- internal/engine/protocol/atproto/data_source.go
- internal/node/component/info/handler_worker.go
- internal/node/monitor/client.go
- internal/node/monitor/monitor.go
- internal/node/monitor/monitor_test.go
- internal/node/monitor/server.go
> fix(monitor): modify the logic of atproto monitor

- internal/node/component/info/handler_node.go
- Extend WorkerCoverage struct with AI support status
- Update GetNodeInfo logging to include AI supported workers
- Modify getNodeWorkerCoverage to handle AI component configuration
- Add AI worker coverage tracking for agentdata
> feat: add AI worker coverage to node info component

- internal/node/component/info/handler_network.go
- internal/node/component/info/network_config.go
- Changed NetworkConfig structure to use NetworkConfigDetailForSingleWorker for both RSS and AI configurations.
- Updated the getNetworkConfigDetailForAI function to return a single worker configuration instead of a slice.
- Removed the genAIConfigDetail function as it was replaced by the new implementation for better clarity and efficiency.
> fix: update network configuration types for AI

- internal/node/component/aggregator/component.go
- Introduced `emptyResponse` function to return a 200 status with an empty data structure.
- Updated methods in both decentralized and federated interfaces to return an empty response when their respective components are nil.
- Ensured consistent handling of nil checks across all relevant methods.
> feat: add empty response handling for components
